/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { MeshBasicMaterial } from "three";

const wireframeMat = new MeshBasicMaterial({wireframe: true, color: '#1e3465'})

export function Palm(props) {
  const { nodes, materials } = useGLTF("/palm.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Node.geometry}
        material={wireframeMat}
        wireframe
      />
    </group>
  );
}

useGLTF.preload("/palm.glb");
