/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { MeshBasicMaterial } from "three";

const wireframeMat = new MeshBasicMaterial({wireframe: true, color: '#1e3465'})

export function Palm(props) {
  const { nodes, materials } = useGLTF("/palm.glb");
  const { palmWireframe, setPalmWireframe } = props;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Node.geometry}
        material={palmWireframe ? wireframeMat : materials.SunshinePalmTree_mat}
        wireframe
        onPointerEnter={() => {setPalmWireframe(true); console.log('enter')}}
        onPointerLeave={() => {setPalmWireframe(false); console.log('leave')}}
      />
    </group>
  );
}

useGLTF.preload("/palm.glb");
